### ISSUE TITLE
Stream Api

### ISSUE THREAD

**Issue by makarov-roman** [peitaosu/LoopbackCapture#1]
Hello. Thanks for the wrappings. It's unique for python for now.  
I have quite simple question, but I'm didn't use c# and windows api before and need your advice. 
Instead of writing to the file I want to return audio as a stream to analyze it with python, how I can do this?

**Comment by peitaosu** [comment]
Hello @makarov-roman,

Sorry for the late reply. I didn't try this but I think you probably can use `clr` in your python code to add assembly `CSCore.dll` and use it to capture loopback and return as a stream.

https://github.com/filoe/cscore
https://pypi.org/project/pythonnet/2.2.2/
